name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: read
      pull-requests: write
    name: CI
    uses: FerrLabs/.github/.github/workflows/reusable-ci-go.yml@88f0161ac0567a4cd82906562d44674dbb89ae67 # main
    with:
      build-paths: ./cmd/...
      enable-sonar: true
    secrets: inherit
