name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: FerrLabs/.github/.github/workflows/reusable-ci-go.yml@4215a840974a9eb611b05f1496ec99d7ba0492c0 # main
    with:
      build-paths: ./cmd/...
      enable-sonar: true
    secrets: inherit
